TouristProject/Controllers/MvcApp/DocsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LetsTravel.Controllers.MvcApp
{
    [Authorize]
    public class DocsController : Controller
    {
        public ActionResult Main()
        {
            return View();
        }
    }
}

TouristProject/Controllers/MvcApp/TripController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using LetsTravel.DAL;
using LetsTravel.DAL.Abstractions;
using LetsTravel.Entities;
using LetsTravel.Entities.OpenWeatherModels;
using LetsTravel.Entities.ViewModels;
using LetsTravel.Helpers;
using Newtonsoft.Json;

namespace LetsTravel.Controllers.MvcApp
{
    [Authorize]
    public class TripController : Controller
    {
        private IOpenWeather weatherHelper;
        private UnitOfWork unitOfWork;
        private GoogleHelper googleHelper;
        private GenericRepository<Place> placeRepository;
        private GenericRepository<Trip> tripRepository;
        private GenericRepository<City> cityRepository;
        private GenericRepository<State> stateRepository;
        private GenericRepository<Country> countryRepository;
        private GenericRepository<Conversation> conversationRepository;

        public TripController()
        {
            this.unitOfWork = new UnitOfWork();
            this.googleHelper = new GoogleHelper();
            this.placeRepository = unitOfWork.GetRepository<Place>();
            this.tripRepository = unitOfWork.GetRepository<Trip>();
            this.cityRepository = unitOfWork.GetRepository<City>();
            this.stateRepository = unitOfWork.GetRepository<State>();
            this.countryRepository = unitOfWork.GetRepository<Country>();
            this.conversationRepository = unitOfWork.GetRepository<Conversation>();
            this.weatherHelper = new OpenWeatherHelper();
        }

        public TripController(ITouristModel touristModel, IOpenWeather weatherHelper)
        {
            this.unitOfWork = new UnitOfWork(touristModel);
            this.googleHelper = new GoogleHelper();
            this.placeRepository = unitOfWork.GetRepository<Place>();
            this.tripRepository = unitOfWork.GetRepository<Trip>();
            this.cityRepository = unitOfWork.GetRepository<City>();
            this.stateRepository = unitOfWork.GetRepository<State>();
            this.countryRepository = unitOfWork.GetRepository<Country>();
            this.conversationRepository = unitOfWork.GetRepository<Conversation>();
            this.weatherHelper = weatherHelper;
        }

        [AllowAnonymous]
        public ActionResult StartView()
        {
            return View();
        }

        public ActionResult CreateTrip()
        {
            return View();
        }

        public ActionResult CheckCreatedTrip()
        {
            return View();
        }

        public ActionResult WeatherForecast()
        {
            return View();
        }

        public ActionResult SubmitCreatedTrip()
        {
            TripViewModel createdTrip = Session["CreatedTrip"] as TripViewModel;
            return View(createdTrip);
        }

        public ActionResult SelectTrip()
        {
            return View();
        }
        public ActionResult ShowPlace(int id)
        {
            Place place = placeRepository.GetByID(id);
            return View(place);
        }

        public ActionResult CreatePlace()
        {
            return View();
        }

        public ActionResult ShowTrip(int id)
        {
            Trip selectedTrip = tripRepository.Get(x => x.Id == id, includeProperties: "PlaceList").SingleOrDefault();
            Session["SelectedTrip"] = selectedTrip;
            return View(selectedTrip);
        }

        [HttpPost]
        public void SubmitCreatedTrip(string id, string duration, string distance)
        {
            string[] ids = id.Split(',');
            string[] durations = duration.Split(',');
            string[] distances = distance.Split(',');

            List<Place> selectedPlaceList = new List<Place>();
            double tripDuration = durations.Select(double.Parse).Sum();
            int tripDistance = distances.Select(int.Parse).Sum();

            foreach (string name in ids)
            {
                var place = placeRepository.GetByID(Int32.Parse(name));
                tripDuration += place.DurationInSeconds;
                selectedPlaceList.Add(place);
            }

            City city = cityRepository.GetByID(selectedPlaceList.First().CityId);
            State state = stateRepository.GetByID(city.StateId);
            Country country = countryRepository.GetByID(state.CountryId);

            string user = User.Identity.Name;
            TripViewModel createdTrip = new TripViewModel
            {
                CountryName = country.Name,
                StateName = state.Name,
                CityName = city.Name,
                Duration = TimeSpan.FromSeconds(tripDuration),
                Distance = tripDistance,
                PlaceList = selectedPlaceList,
                UserLogin = user,
            };

            Session["CreatedTrip"] = createdTrip;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCreatedTrip(TripViewModel trip)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string filePath = string.Empty;
                    if (trip.TripPhoto != null && trip.TripPhoto.ContentLength > 0)
                    {
                        string fileName = System.IO.Path.GetFileName(trip.TripPhoto.FileName.ToLower());
                        string fileExtension = System.IO.Path.GetExtension(fileName);
                        Guid photoId = Guid.NewGuid();
                        filePath = $"/Content/Images/{trip.CountryName.ToLower()}/{trip.StateName.ToLower()}/{trip.CityName.ToLower()}/{photoId}{fileExtension}";
                        string path = Server.MapPath(filePath);
                        FileInfo fi = new FileInfo(path);
                        fi.Directory.Create();
                        trip.TripPhoto.SaveAs(path);
                    }

                    List<Place> newPlaceList = new List<Place>();
                    foreach (var place in trip.PlaceList)
                    {
                        newPlaceList.Add(placeRepository.GetByID(place.Id));
                    }

                    Mapper.Initialize(x => x.CreateMap<TripViewModel, Trip>()
                        .ForMember("DistanceInMeters", opt => opt.MapFrom(c => c.Distance))
                        .ForMember("DurationInSeconds", opt => opt.MapFrom(c => trip.Duration.TotalSeconds))
                        .ForMember("TripPrice", opt => opt.MapFrom(src => Convert.ToDecimal(trip.TripPrice, CultureInfo.InvariantCulture)))
                        .ForMember("Photo", opt => opt.MapFrom(src => filePath))
                        .ForMember("PlaceList", opt => opt.MapFrom(src => newPlaceList)));

                    Trip newTrip = Mapper.Map<TripViewModel, Trip>(trip);

                    int tripId = tripRepository.Get(x => x.TripName.ToLower() == trip.TripName.ToLower()).Select(x => x.Id).SingleOrDefault();
                    if (tripId == 0)
                    {
                        tripRepository.Insert(newTrip);
                        unitOfWork.Save();
                    }

                    return RedirectToAction("StartView");
                }
                else
                {
                    return View("SubmitCreatedTrip", trip);
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View("CreateTrip");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePlace(PlaceViewModel country)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string filePath = string.Empty;
                    if (country.PlacePhoto != null && country.PlacePhoto.ContentLength > 0)
                    {
                        string fileName = System.IO.Path.GetFileName(country.PlacePhoto.FileName.ToLower());
                        string fileExtension = System.IO.Path.GetExtension(fileName);
                        filePath = $"/Content/Images/{country.CountryName.ToLower()}/{country.StateName.ToLower()}/{country.CityName.ToLower()}/{country.GooglePlaceId}{fileExtension}";
                        string path = Server.MapPath(filePath);
                        FileInfo fi = new FileInfo(path);
                        fi.Directory.Create();
                        country.PlacePhoto.SaveAs(path);
                    }

                    double latitude = default(double);
                    if (country.Latitude != null)
                    {
                        latitude = double.Parse(country.Latitude, CultureInfo.InvariantCulture);
                    }

                    double longitude = default(double);
                    if (country.Longitude != null)
                    {
                        longitude = double.Parse(country.Longitude, CultureInfo.InvariantCulture);
                    }

                    double rating = default(double);
                    if (country.Rating != null)
                    {
                        rating = double.Parse(country.Rating, CultureInfo.InvariantCulture);
                    }

                    Mapper.Initialize(x => x.CreateMap<PlaceViewModel, Place>()
                        .ForMember("Name", opt => opt.MapFrom(c => country.PlaceName))
                        .ForMember("Latitude", opt => opt.MapFrom(c => latitude))
                        .ForMember("Longitude", opt => opt.MapFrom(c => longitude))
                        .ForMember("DurationInSeconds", opt => opt.MapFrom(c => country.Duration.TotalSeconds))
                        .ForMember("Photo", opt => opt.MapFrom(c => filePath))

TouristProject/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

TouristProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript" src="~/Scripts/Layout.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "StartView", "Trip")</li>
                    <li>@Html.ActionLink("Weather Forecast", "WeatherForecast", "Trip")</li>
                    <li>@Html.ActionLink("API", "Main", "Docs")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div id="chat" class="chat">
            <div id="chatContainer" class="chatContainer">
                <input type="hidden" id="owner" />
                <input type="hidden" id="guest" />
                <div id="discussion"></div>
            </div>
            <div class="input-group chatInputGroup">
                <input type="text" class="form-control chatInputText" id="message" name="message" placeholder="Enter your message!" value="" style="width:205px">
                <button id="sendMessage" class="btn btn-default" type="button">Send</button>
            </div>
        </div>

        <div id="slideout" title="Users online:">
            <div id="slideTitle">
                <strong>
                    Users online:
                </strong>
            </div>
            <div id="slidecontent">
            </div>
            <div id="clickme">
            </div>
        </div>

        @RenderBody()
        <footer>
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>